"""Add OTP lock and Hash Refresh Token

Revision ID: 462cb9ab670d
Revises: 459889842bec
Create Date: 2026-10-07 16:38:23.757768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462cb9ab670d'
down_revision = '459889842bec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('escalation_stage', sa.Integer(), nullable=True),
    sa.Column('escalation_status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_elder_id'), 'alert_notifications', ['elder_id'], unique=False)
    op.create_index(op.f('ix_alert_notifications_id'), 'alert_notifications', ['id'], unique=False)
    op.create_table('voice_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_calls_elder_id'), 'voice_calls', ['elder_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_id'), 'voice_calls', ['id'], unique=False)
    op.alter_column('activities', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_activities_elder_id'), 'activities', ['elder_id'], unique=False)
    op.create_index(op.f('ix_call_records_elder_id'), 'call_records', ['elder_id'], unique=False)
    op.add_column('elder_profiles', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('elder_profiles', sa.Column('medical_info', sa.JSON(), nullable=True))
    op.add_column('elder_profiles', sa.Column('routines', sa.JSON(), nullable=True))
    op.add_column('elder_profiles', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.alter_column('elder_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('refresh_tokens', sa.Column('hashed_token', sa.String(), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_hashed_token'), 'refresh_tokens', ['hashed_token'], unique=True)
    op.drop_column('refresh_tokens', 'token')
    op.alter_column('user_relationships', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_relationships', 'caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_lock_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_otp_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp_requested_at')
    op.drop_column('users', 'otp_lock_until')
    op.drop_column('users', 'phone_number')
    op.alter_column('user_relationships', 'caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_relationships', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_hashed_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=1)
    op.drop_column('refresh_tokens', 'hashed_token')
    op.alter_column('elder_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('elder_profiles', 'emergency_contact')
    op.drop_column('elder_profiles', 'routines')
    op.drop_column('elder_profiles', 'medical_info')
    op.drop_column('elder_profiles', 'preferences')
    op.drop_index(op.f('ix_call_records_elder_id'), table_name='call_records')
    op.drop_index(op.f('ix_activities_elder_id'), table_name='activities')
    op.alter_column('activities', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_voice_calls_id'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_elder_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_index(op.f('ix_alert_notifications_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_elder_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    # ### end Alembic commands ###
