"""Add Reminder and Occurrence models

Revision ID: 4fd82bf79812
Revises: 84667f96d982
Create Date: 2026-10-07 16:48:04.035061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd82bf79812'
down_revision = '84667f96d982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('recurrence', sa.String(), nullable=False),
    sa.Column('times', sa.JSON(), nullable=True),
    sa.Column('dates', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_elder_id'), 'reminders', ['elder_id'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id', 'due_at', name='uix_reminder_due_at')
    )
    op.create_index(op.f('ix_occurrences_id'), 'occurrences', ['id'], unique=False)
    op.create_index(op.f('ix_occurrences_reminder_id'), 'occurrences', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_occurrences_status'), 'occurrences', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('user_relationships', 'caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_relationships', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elder_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('elder_profiles', 'emergency_contact')
    op.drop_column('elder_profiles', 'routines')
    op.drop_column('elder_profiles', 'medical_info')
    op.drop_column('elder_profiles', 'preferences')
    op.drop_index(op.f('ix_call_records_elder_id'), table_name='call_records')
    op.drop_index(op.f('ix_activities_elder_id'), table_name='activities')
    op.alter_column('activities', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_occurrences_status'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_reminder_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_elder_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
