"""Add Message model

Revision ID: 84667f96d982
Revises: 941ae7daa8ce
Create Date: 2026-10-07 15:45:31.368007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84667f96d982'
down_revision = '941ae7daa8ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_elder_id'), 'messages', ['elder_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.alter_column('user_relationships', 'caregiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_relationships', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elder_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('elder_profiles', 'emergency_contact')
    op.drop_column('elder_profiles', 'routines')
    op.drop_column('elder_profiles', 'medical_info')
    op.drop_column('elder_profiles', 'preferences')
    op.drop_index(op.f('ix_call_records_elder_id'), table_name='call_records')
    op.drop_index(op.f('ix_activities_elder_id'), table_name='activities')
    op.alter_column('activities', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_voice_calls_id'), table_name='voice_calls')
    op.drop_index(op.f('ix_voice_calls_elder_id'), table_name='voice_calls')
    op.drop_table('voice_calls')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_elder_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_alert_notifications_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_elder_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    # ### end Alembic commands ###
